export const municipios = [
  { municipioId: 1, provinciaId: 1, name: "Santo Domingo de Guzmán" },
  { municipioId: 2, provinciaId: 2, name: "Azua" },
  { municipioId: 3, provinciaId: 2, name: "Estebanía" },
  { municipioId: 4, provinciaId: 2, name: "Las Charcas" },
  { municipioId: 5, provinciaId: 3, name: "Neiba" },
  { municipioId: 6, provinciaId: 3, name: "Galván" },
  { municipioId: 7, provinciaId: 4, name: "Barahona" },
  { municipioId: 8, provinciaId: 4, name: "Cabral" },
  { municipioId: 9, provinciaId: 5, name: "Dajabón" },
  { municipioId: 10, provinciaId: 6, name: "San Francisco de Macorís" },
  { municipioId: 11, provinciaId: 6, name: "Arenoso" },
  { municipioId: 12, provinciaId: 7, name: "Comendador" },
  { municipioId: 13, provinciaId: 8, name: "Santa Cruz de El Seibo" },
  { municipioId: 14, provinciaId: 9, name: "Moca" },
  { municipioId: 15, provinciaId: 10, name: "Hato Mayor del Rey" },
  { municipioId: 16, provinciaId: 11, name: "Salcedo" },
  { municipioId: 17, provinciaId: 12, name: "Jimaní" },
  { municipioId: 18, provinciaId: 13, name: "Higüey" },
  { municipioId: 19, provinciaId: 14, name: "La Romana" },
  { municipioId: 20, provinciaId: 15, name: "La Vega" },
  { municipioId: 21, provinciaId: 16, name: "Nagua" },
  { municipioId: 22, provinciaId: 17, name: "Bonao" },
  { municipioId: 23, provinciaId: 18, name: "Monte Cristi" },
  { municipioId: 24, provinciaId: 19, name: "Monte Plata" },
  { municipioId: 25, provinciaId: 20, name: "Pedernales" },
  { municipioId: 26, provinciaId: 21, name: "Baní" },
  { municipioId: 27, provinciaId: 22, name: "Puerto Plata" },
  { municipioId: 28, provinciaId: 23, name: "Samaná" },
  { municipioId: 29, provinciaId: 24, name: "San Cristóbal" },
  { municipioId: 30, provinciaId: 25, name: "San José de Ocoa" },
  { municipioId: 31, provinciaId: 26, name: "San Juan" },
  { municipioId: 32, provinciaId: 27, name: "San Pedro de Macorís" },
  { municipioId: 33, provinciaId: 28, name: "Cotuí" },
  { municipioId: 34, provinciaId: 29, name: "Santiago" },
  { municipioId: 35, provinciaId: 30, name: "Santiago Rodríguez" },
  { municipioId: 36, provinciaId: 31, name: "Santo Domingo Este" },
  { municipioId: 37, provinciaId: 31, name: "Santo Domingo Oeste" },
  { municipioId: 38, provinciaId: 31, name: "Santo Domingo Norte" },
  { municipioId: 39, provinciaId: 32, name: "Mao" },
];
