@EvaluacionFarmaciaAPI_HostAddress = http://localhost:5041

GET {{EvaluacionFarmaciaAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{{{EvaluacionFarmaciaAPI_HostAddress}}}}/api/DrugStores HTTP/1.1
Accept: application/json



